-- LIKE KEYWORD SEARCHES FOR MATCHED IN THE COLUMn
--    % - ALL CHARACTERS ALLOWED BEFORE THE KEYWORD
--      EXAMPLE : %LOVE% - FINDS LOVE IN THE MIDDLE 
--                %LOVE  - FINDS LOVE IN THE LAST
--                LOVE%  - FINDS LOVE IN THE BEGINNING 
--      WARNING! : THE% WILL ALSO MATCH (THE,THEY,THERE)
--                 TO AVOID WARNING WE ADD SPACE AFTER WORD
SELECT * FROM "users" WHERE "name" LIKE '%john%';

--SUPPOSE U FORGOT A CHARACTER IN BETWEEN A WORD U WANT TO SEARCH THEN U USE
SELECT * FROM "users" WHERE "name" LIKE '__hn';
